l_russian:
 carnx_slave_price_base_desc: "Base"
 carnx_slave_price_claims_desc: "Claims"
 carnx_slave_price_dynasty_desc: "Dynasty"
 carnx_slave_price_traits_desc: "Traits"
 carnx_slave_price_skills_desc: "Skills"
 carnx_slave_price_attraction_desc: "Attraction"
 carnx_slave_price_visibly_fertile_female_desc: "Visibly Fertile Female"
 carnx_slave_price_age_desc: "Age"
 carnx_slave_price_multiplier_desc: "Balance Multiplier"
 carnx_slave_price_min_desc: "Minimum Price"
 carnx_slave_price_player_desc: "Profit Margin"
 carnx_slave_price_government_desc: "Tribal or Nomadic Government"
 carnx_slave_price_seller_greed_desc: "Seller Greed"
 carnx_slave_price_buyer_greed_desc: "Buyer Greed"
 carnx_slave_price_seller_attitude_desc: "Seller Slavery Attitude"
 carnx_slave_price_buyer_attitude_desc: "Buyer Slavery Attitude"
 carnx_slave_bid_price_multiplier_desc: "Haggle Outcome"